### ISSUE TITLE
Provide definitions Java Classes as artifacts on maven central

### ISSUE THREAD

**Issue by ManuelB** [DKE-Data/agrirouter-api-protobuf-definitions#17]
It would be awesome if we can consume the definitions from maven central as a never changing versioned java archive that fullfills the requirements (https://central.sonatype.org/pages/requirements.html) e.g. signed, official licensed etc.

The coordinates should be:

```
<dependency>
    <groupId>com.dke.data.api.protobuf</groupId>
    <artifactId>agrirouter-api-protobuf-definitions</artifactId>
    <version>0.0.1</version>
</dependency>
```

The guide how to publish to maven central can be found here:
https://central.sonatype.org/pages/ossrh-guide.html

**Comment by saschadoemer** [comment]
Yeah, that would be awesome 😃 

All the points you mentioned - signed, official licencse - are fullfilled. Not the first open source project 😛 

Coordinated will be, due to formal reasons.

```
<dependency>
    <groupId>com.agrirouter.protobuf</groupId>
    <artifactId>agrirouter-api-protobuf-definitions</artifactId>
    <version>0.0.1</version>
</dependency>
```

Current coordinates are not possible, because DKE does not own http://www.dke.com.

**Comment by ManuelB** [comment]
@saschadoemer awesome! I will add this issue to our internal tracking and as soon as the artifacts are published we will remove our internal management of this dependency.
