### ISSUE TITLE
Provide definitions with jdk8 classifier for Java Classes as artifacts on maven central

### ISSUE THREAD

**Issue by ManuelB** [DKE-Data/agrirouter-api-protobuf-definitions#18]
It would be cool to release artifacts compiled with Java 8 e.g. with a classifier:

```
<dependency>
    <groupId>com.agrirouter.protobuf</groupId>
    <artifactId>agrirouter-api-protobuf-definitions</artifactId>
    <version>0.0.1</version>
    <classifier>jdk8</classifier>
</dependency>
```

https://stackoverflow.com/a/10929578/1059979

**Comment by saschadoemer** [comment]
@ManuelB Keeping you up to date. The implementation is already merged (see #19 for more details), artifacts are available as SNAPSHOTS. I will close the issue after the release has been build.
