### ISSUE TITLE
Spelling error in EnpointRegistrationDetails

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-api-protobuf-definitions#23]
The name of EnpointRegistrationDetails should be EndpointRegistrationDetails.
The d of En>d<point is missing.

Please fix that

**Comment by Frank-Wiebeler** [comment]
@saschadoemer  Yes, at least the right repository. The error is in the .proto file  agrirouter-api-protobuf-definitions/src/main/resources/com/dke/data/agrirouter/proto/cloud-provider-integration/cloud-virtualized-app-registration.proto  

I know, that this change has impact for any agrirouter implementation (if they recompile the protobuf), but yes, the spelling error is in this repository. 

I would recomment to fix it either now or on a specific date during winter, so that every app provider is aware of this change.

**Comment by saschadoemer** [comment]
Can be done when the new protobuf definition is delivered.

**Comment by Frank-Wiebeler** [comment]
DONE
