### ISSUE TITLE
Remove inconsistencies in proto files

### ISSUE THREAD

**Issue by doekermk** [DKE-Data/agrirouter-api-protobuf-definitions#31]
Field names should be underscore_separated_names, see [protobuf style guide](https://developers.google.com/protocol-buffers/docs/style). The file [cloud-virtualized-app-registration.proto](https://github.com/DKE-Data/agrirouter-api-protobuf-definitions/blob/develop/src/main/resources/com/dke/data/agrirouter/proto/cloud-provider-integration/cloud-virtualized-app-registration.proto) should be updated.

Compare [EndpointRegistrationDetails](https://github.com/DKE-Data/agrirouter-api-protobuf-definitions/blob/develop/src/main/resources/com/dke/data/agrirouter/proto/cloud-provider-integration/cloud-virtualized-app-registration.proto) (which is not correct)

```
string deviceAlternateId = 2;
string sensorAlternateId = 3;
string capabilityAlternateId = 4
string endpointId = 5;
```
and [HeaderQueryResponse ](https://github.com/DKE-Data/agrirouter-api-protobuf-definitions/blob/2a1129330bc37fb2fe717cf61dc8db72295a6abc/src/main/resources/com/dke/data/agrirouter/proto/messaging/response/payload/feed/feed-response.proto) (which is correct)
```
string message_id = 1;
string technical_message_type = 2;  
```

**Comment by agrirouter** [comment]
Is fixed.
