### ISSUE TITLE
Built a Capability with a missing 'direction' property when set a "SEND" direction.

### ISSUE THREAD

**Issue by tsvetanv** [DKE-Data/agrirouter-api-protobuf-definitions#33]
Hello all,
I have an issue which I can not solve and need your help.

**Issue Description**
When I build a capability with direction "SEND", the builder generates a capability with a missing 'direction' property:

`    Capability capab1 = Capability.newBuilder().setDirection(Direction.SEND)
        .setTechnicalMessageType(TechnicalMessageType.ISO_11783_TASKDATA_ZIP.getTechnicalMessageName()).build();
`
The output is the following:
`
 "capabilities": [{
      "technicalMessageType": "iso:11783:-10:taskdata:zip"
    }]
`

**Expected behavior**
It is expected the generated capability to have 2 properties: technicalMessageType & direction.

**Additional context**
I use:
- the latest 0.0.1-SNAPSHOT version of agrirouter-api-protobuf-definitions (2018-12-31).
- JVM: 1.8.0_144
- Maven: Apache Maven 3.5.0

**Additional Tests**
When I build a capability with direction "SEND_RECEIVE", everything is fine:
` 
    Capability capab2 = Capability.newBuilder().setDirection(Direction.SEND_RECEIVE)
        .setTechnicalMessageType(TechnicalMessageType.ISO_11783_TASKDATA_ZIP.getTechnicalMessageName()).build();
`
The output is fine as expected:
`"capabilities": [{
      "technicalMessageType": "iso:11783:-10:taskdata:zip",
      "direction": "SEND_RECEIVE"
    }]`
Do I miss something?

**Comment by Frank-Wiebeler** [comment]
The value of the enum "SEND" is 0. 
Protobuf interpretes this as a "not set" or "default" value, from the sending side as on the server side. The client sends only the TechnicalMessageType, so the server assumes the direction value to be 0 = SEND. Therefor, it is not returned in the JSON interpretation.
This is a general behavior of protobuf and should not cause problems, I'll however mention this in the documentation.



Does that knowledge fix your issue?

**Comment by tsvetanv** [comment]
Yes, thank you very much.
